export const GET_ALL_SONGS = 'GET_ALL_SONGS';
export const DISABLE_SONG = 'DISABLE_SONG';
export const GET_SONG = 'GET_SONG';
export const UPDATE_SONG = 'UPDATE_SONG';
export const UPDATE_SONG_DESCRIPTION_START = 'UPDATE_SONG_DESCRIPTION_START';
export const UPDATE_SONG_DESCRIPTION_SUCCESS = 'UPDATE_SONG_DESCRIPTION_SUCCESS';
export const UPDATE_SONG_DESCRIPTION_FAILURE = 'UPDATE_SONG_DESCRIPTION_FAILURE';